### ISSUE TITLE
Some VC titles not showing in menu

### ISSUE THREAD

**Issue by EnderSteveCreep** [emiyl/dumpling#17]
I’m trying to dump Japanese VC titles, and the majority of them fail to show up in the “Dump digital games” menu. The only successful game was a GBA title with no Japanese characters in its name, which leads me to believe that the text happens to be the cause, not the region. On launch, I see this several times over:

“Could only parse 6 information bits:
shortname_en = Undisplayable Game Name [some game ID(different for each game)]
product_code = (same code from above)
Failed to read meta from game!”

**Comment by TakuikaNinja** [comment]
I just ran into the same issue today. 
From what I can tell from the code in titles.cpp, a generic short title is used when the game has non-standard characters. However, the flag to denote that the short title has been found doesn't get updated afterwards. 
I believe removing the "else" from line 36 in said file would fix this but I don't have an development environment to test it in.

**Comment by Crementif** [comment]
I'm currently working on adding freetype2 which will things a lot more usable by allowing differently sized letters and show non-english characters. So that should get rid of the undisplayable game names.

About the issue of the japanese VC titles not appearing, I'd be curious to know what the file inside the game's meta->meta.xml looks like. The error at the beginning would indeed make it not show up. If you haven't gotten it dumped or don't really want/know how to dump it, what games did you find that had this issue? I can try to buy them.

**Comment by TakuikaNinja** [comment]
The Japanese ones I have are Brain Age, Mario & Luigi RPG (this one was displayed with corrupt characters iirc), Kirby & the Amazing Mirror, Pinball, and SMB1.

**Comment by Crementif** [comment]
Found a fix which'll be in an official release soon, but I'll keep it open till you guys are able to test it. It seems like you were absolutely on the money with that suggested fix @TakuikaNinja haha. I also added freetype2 since this so now kanji will be displayed too in the next major release. Thanks for the patience.

**Comment by Crementif** [comment]
New release is out with a lot of fixes addressing some prior shortcomings. Let me know if everything dumps correctly now if you've got the time.

**Comment by TakuikaNinja** [comment]
All the titles I have are shown properly now, and I was able to dump Brain Age. Thanks!

**Comment by Crementif** [comment]
Awesome! Thanks for the testing and reporting the issue.
